#-------------------------------
# General Site Settings

title: Web Designer
description: Father // Freelancer // Designer // Developer // Cyclist
email: grant@transitiongraphics.co.uk

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Grant Smith, Web Designer based in Gloucestershire.'
  rel-author: 'https://plus.google.com/+TransitiongraphicsCoUkGraphics'
  rel-publisher: 'https://plus.google.com/+TransitiongraphicsCoUkGraphics'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
    <p><strong>Grant Smith is the Creative Director of <a href="//www.transitiongraphics.co.uk" title="Responsive, engaging webdesign from Transition Graphics" target="_blank">Transition Graphics</a></strong>, a company he started in early 2014. Within this time, Grant has built up an impressive client list including <a href="//www.sonymusic.co.uk" title="Sony Music UK" target="_blank">Sony Music</a>, <a href="//www.forestry.gov.uk/england" title="Forestry Commision England" target="_blank">Forestry Commission England</a> and <a href="//www.costain.com" title="Engineering a Sustainable Tomorrow" target="_blank">Costain</a>.</p>
     <p>His professional career started in 1997 within photography but soon moved towards other areas of visual communication, more specifically print design and production. During this time, Grant has found a real passion for expanding his creative knowledge while developing existing experience. This has led to a very rounded skill set ranging from brand communications to e-commerce web development.</p>
     <p>Before Transition Graphics, Grant worked with a wide variety of companies and as his skills in design developed he came to the realisation that his heart lay in helping SME’s to grow through better visual communications. Transition Graphics goal is to provide SME’s with agency standards without agency costs.</p>
     <p>Grant lives in Gloucestershire with partner Karla and daughter Seren, in his free time, he is often found cycling the local hills.</p>


skills:
- {name: Communication, value: '10'}
- {name: Organization, value: '7'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '7'}
- {name: Planning, value: '10'}
- {name: Visual Design, value: '8'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '8'}

#-------------------------------
# Work Section

projects:
- {name: Cynero, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: 113 Events, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Rackham Effect, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: DBMax Sports Timing, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Loma Consulting, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Liz Clegg Executive Coaching, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Sandford Parks Lido, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Amanda McGough, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-graemeh.jpg',
  name: 'Graeme Hardie',
  title: 'Director, 113 Events.',
  quote: '<p><strong>I used Grant at Transition Graphics</strong> for the design, development and ongoing maintenance of my business website this year. I have found them to be very professional, always very punctual and provide great value for money. I’ll be the first person to admit that I’m not graphically talented, or any good at all at what works and what doesn’t, and Grant took the time to explain how different elements of the site work and created all the graphical content himself in a format that’s both complex, but understandable. Our website now has a modern feel and a slick operation, and it’s helped our business engage with a more professional audience. I wouldn’t hesitate to recommend Transition Graphics for any other projects.</p>',
  logo: 'logo1.svg'}
- {avatar: 'face-lizc.jpg',
  name: 'Liz Clegg',
  title: 'Director, Executive Coach and HR Consultant',
  quote: '<p><strong>You only get one go at a website, so it has to be the best it can possibly be.</strong> Grant not only has excellent technical skills, but he works closely with you to develop a deep understanding of your business and how you want to be portrayed. Grant didn’t rush me into making decisions, but when the ball was in his court he delivered promptly. He was happy to try out different options and above all wanted to ensure that I was satisfied at every stage. Working with Grant to develop my website was an enjoyable experience and I am delighted with the outcome. I have had excellent feedback on the site from colleagues and customers.</p>',
  logo: 'logo2.svg'}
- {avatar: 'face-Jamesh.png',
  name: 'James Higgs',
  title: Event Director, DB Max',
  quote: '<p><strong>Grant at Transition Graphics has provided us with a fantastic service since day one.</strong> From a thorough review of the website and what we need to its development and implementation and beyond. I would thoroughly recommend Grant to anyone looking to update their website.</p>',
  logo: 'logo3.svg'}
- {avatar: 'face-LouiseM.jpg',
  name: 'Louise May',
  title: 'Dirctor, Loma Consulting.',
  quote: '<p><strong>I am delighted with my new brand and website.</strong> Grant is knowledgable, professional and patient. He teased my requirements out of me very skilfully and then created a modern, fresh identity for my business including a strong logo, a beautiful website and a range of stationery. I run a niche executive search business and my customers are senior people in large organisations, so my brand needs to be polished and my website needs to be concise and professional.  My window on the world now reflects my business and its values perfectly. Thank you Transition Graphics!</p>',
  logo: 'logo4.svg'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/GrantTransition'}
- {icon: 'linkedin', link: 'https://uk.linkedin.com/in/transitiongraphics'}
- {icon: 'instagram', link: 'https://www.instagram.com/grantsmith/'}
- {icon: 'github', link: 'https://github.com/granttransition'}
- {icon: 'google-plus', link: 'https://plus.google.com/+TransitiongraphicsCoUkGraphics'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
